CREATE USER c##ordersys IDENTIFIED BY 123123;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE TO c##ordersys;

GRANT INSERT, SELECT, UPDATE, DELETE ON Customers TO c##ordersys;
GRANT INSERT, SELECT, UPDATE, DELETE ON Products TO c##ordersys;
GRANT INSERT, SELECT, UPDATE, DELETE ON Orders TO c##ordersys;
GRANT INSERT, SELECT, UPDATE, DELETE ON Administraters TO c##ordersys;
GRANT INSERT, SELECT, UPDATE, DELETE ON Order_items TO c##ordersys;

ALTER USER c##ordersys QUOTA UNLIMITED ON USERS;
