CREATE TABLE Pet (
  PET_ID NUMBER(10) PRIMARY KEY,
  PET_NAME VARCHAR2(50) NOT NULL,
  PET_TYPE VARCHAR2(50) NOT NULL,
  PET_COLOUR VARCHAR2(50) NOT NULL
);

INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (1, 'Fluffy', 'Cat', 'White');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (2, 'Max', 'Dog', 'Brown');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (3, 'Charlie', 'Dog', 'Black');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (4, 'Buddy', 'Dog', 'Golden');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (5, 'Luna', 'Cat', 'Grey');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (6, 'Rocky', 'Dog', 'White');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (7, 'Tiger', 'Cat', 'Orange');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (8, 'Oreo', 'Cat', 'Black and White');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (9, 'Daisy', 'Dog', 'White and Brown');
INSERT INTO Pet (PET_ID, PET_NAME, PET_TYPE, PET_COLOUR) VALUES (10, 'Milo', 'Cat', 'Tabby');

commit;


SELECT * FROM PRODUCTS;